// Copyright (c) 2026 Cerid AI. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import type { SettingDef } from "./types"

export const EXTENSIONS_DEFS: SettingDef[] = [
  // ── Plugins ────────────────────────────────────────────────────────────────
  {
    id: "extensions.plugins.scan",
    category: "extensions",
    group: "plugins",
    level: "core",
    label: "Scan for plugins",
    helpText: "Re-scan the plugin directory for newly installed plugins.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["plugin", "scan", "discover", "install", "Plugins"],
    type: "action",
    writer: { kind: "endpoint", method: "POST", path: "/plugins/scan" },
  },
  {
    id: "extensions.plugins.enable",
    category: "extensions",
    group: "plugins",
    level: "core",
    label: "Enable plugin",
    helpText: "Enable or disable an installed plugin. Enterprise-tier plugins are disabled for lower tiers.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["plugin", "enable", "disable", "toggle", "Plugins"],
    type: "boolean",
    writer: { kind: "endpoint", method: "POST", path: "/plugins/{name}/enable" },
  },
  {
    id: "extensions.plugins.config",
    category: "extensions",
    group: "plugins",
    level: "advanced",
    label: "Plugin configuration",
    helpText: "Key-value configuration for a plugin. Values are stored as strings; the plugin interprets types.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["plugin", "config", "configuration", "settings", "Plugins"],
    type: "string",
    writer: { kind: "endpoint", method: "PUT", path: "/plugins/{name}/config" },
  },
  // ── MCP Governance ─────────────────────────────────────────────────────────
  {
    id: "extensions.mcp.mode",
    category: "extensions",
    group: "mcp",
    level: "core",
    label: "MCP client mode",
    helpText: "Controls which external MCP servers agents may call. \"Permissive\" allows all. \"Allowlist\" restricts to the listed servers. \"Disabled\" blocks all external tools.",
    scopeOfEffect: {
      scope: "env",
      display: "Read-only here — set MCP_CLIENT_MODE in .env and restart.",
    },
    keywords: ["MCP", "client", "mode", "permissive", "allowlist", "disabled", "governance", "Governance"],
    type: "display",
    writer: { kind: "env", envVar: "MCP_CLIENT_MODE" },
  },
  {
    id: "extensions.mcp.allowlist",
    category: "extensions",
    group: "mcp",
    level: "core",
    label: "MCP allowlist",
    helpText: "Comma-separated server names permitted in allowlist mode. Set MCP_CLIENT_ALLOWLIST in .env.",
    scopeOfEffect: {
      scope: "env",
      display: "Read-only here — set MCP_CLIENT_ALLOWLIST in .env and restart.",
    },
    keywords: ["MCP", "allowlist", "whitelist", "servers", "governance", "Governance"],
    type: "display",
    writer: { kind: "env", envVar: "MCP_CLIENT_ALLOWLIST" },
  },
  {
    id: "extensions.mcp.strictAgents",
    category: "extensions",
    group: "mcp",
    level: "core",
    label: "Strict agents only",
    helpText: "When enabled, only pre-audited agent definitions may run — no dynamic tool composition. Set STRICT_AGENTS_ONLY in .env.",
    scopeOfEffect: {
      scope: "env",
      display: "Read-only here — set STRICT_AGENTS_ONLY in .env and restart.",
    },
    keywords: ["strict", "agents", "STRICT_AGENTS_ONLY", "governance", "Governance"],
    type: "display",
    writer: { kind: "env", envVar: "STRICT_AGENTS_ONLY" },
  },
  {
    id: "extensions.mcp.addServer",
    category: "extensions",
    group: "mcp",
    level: "core",
    label: "Add MCP server",
    helpText: "Register an external MCP server. Choose transport (stdio or SSE), supply the command/URL, and optionally add environment variables or headers containing secrets.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["MCP", "server", "add", "register", "connect", "stdio", "SSE", "Governance"],
    type: "action",
    writer: { kind: "endpoint", method: "POST", path: "/mcp-servers" },
  },
  // ── External APIs ──────────────────────────────────────────────────────────
  {
    id: "extensions.externalApis.enable",
    category: "extensions",
    group: "externalApis",
    level: "core",
    label: "External knowledge providers",
    helpText: "Enable or disable individual external knowledge providers (Wikipedia, arXiv, GitHub, etc.) — read-only sources the retrieval pipeline can search. Adapters marked \"Needs key\" require the corresponding API-key env var before they can be enabled.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["external", "API", "adapter", "knowledge", "providers", "wikipedia", "arxiv", "github", "search", "Governance"],
    type: "boolean",
    writer: { kind: "endpoint", method: "POST", path: "/external-apis/{slug}/enabled" },
  },
  // ── Pro Automations ────────────────────────────────────────────────────────
  {
    id: "extensions.automations.enable",
    category: "extensions",
    group: "automations",
    level: "core",
    label: "Pro automations",
    helpText: "Scheduled background tasks (inbox triage, daily digest). Cadence is configurable per-automation. Schedules persist to Redis and override CERID_* env defaults.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["automation", "scheduled", "background", "inbox", "digest", "Pro", "System"],
    type: "boolean",
    entitlement: "pro",
    featureFlag: "pro_meeting_capture",
    writer: { kind: "endpoint", method: "PUT", path: "/settings/pro-automations/{name}" },
  },
  {
    id: "extensions.automations.cadence",
    category: "extensions",
    group: "automations",
    level: "core",
    label: "Automation cadence",
    helpText: "When each automation runs. Presets cover common intervals; custom shows the raw cron expression.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["automation", "schedule", "cron", "cadence", "interval", "Pro", "System"],
    type: "enum",
    options: [
      { value: "0 8 * * *", label: "Daily at 8 AM" },
      { value: "0 */6 * * *", label: "Every 6 hours" },
      { value: "0 * * * *", label: "Hourly" },
    ],
    entitlement: "pro",
    featureFlag: "pro_meeting_capture",
    writer: { kind: "endpoint", method: "PUT", path: "/settings/pro-automations/{name}" },
  },
]
