// Copyright (c) 2026 Cerid AI. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import type { SettingDef } from "./types"

export const KNOWLEDGE_DEFS: SettingDef[] = [
  // ── Watched Folders ────────────────────────────────────────────────────────
  {
    id: "knowledge.folders.add",
    category: "knowledge",
    group: "folders",
    level: "core",
    label: "Watched Folders",
    helpText: "Directories Cerid auto-ingests. Add a path and Cerid monitors it for new and changed files.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["watch", "folder", "directory", "ingest", "path", "System", "Essentials"],
    type: "action",
    writer: { kind: "endpoint", method: "POST", path: "/watched-folders" },
  },
  {
    id: "knowledge.folders.scan",
    category: "knowledge",
    group: "folders",
    level: "core",
    label: "Scan folder now",
    helpText: "Trigger an immediate re-scan of a watched folder to pick up changes without waiting for the next scheduled sweep.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["scan", "rescan", "ingest", "trigger", "System"],
    type: "action",
    writer: { kind: "endpoint", method: "POST", path: "/watched-folders/{id}/scan" },
  },
  {
    id: "knowledge.folders.remove",
    category: "knowledge",
    group: "folders",
    level: "core",
    label: "Remove watched folder",
    helpText: "Stop watching this folder. Existing ingested content is not deleted.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["remove", "delete", "unwatch", "folder", "System"],
    type: "action",
    danger: "confirm",
    writer: { kind: "endpoint", method: "DELETE", path: "/watched-folders/{id}" },
  },
  // ── Vault Config ───────────────────────────────────────────────────────────
  {
    id: "knowledge.vault.isVault",
    category: "knowledge",
    group: "vault",
    level: "core",
    label: "This folder is a vault",
    helpText: "Enable Obsidian-style markdown vault semantics — Cerid uses subfolder names (MOCs, daily notes, templates) to infer document roles.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["vault", "obsidian", "markdown", "folder", "System"],
    type: "boolean",
    default: false,
    writer: { kind: "endpoint", method: "PUT", path: "/watched-folders/{id}" },
  },
  {
    id: "knowledge.vault.mocsFolder",
    category: "knowledge",
    group: "vault",
    level: "advanced",
    label: "MOCs folder",
    helpText: "Subfolder name for Maps of Content (index/hub notes). Overrides the .cerid-vault.yaml field if that file is absent.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["moc", "map of content", "vault", "index", "hub", "System"],
    type: "string",
    writer: { kind: "endpoint", method: "PUT", path: "/watched-folders/{id}" },
  },
  {
    id: "knowledge.vault.dailyFolder",
    category: "knowledge",
    group: "vault",
    level: "advanced",
    label: "Daily notes folder",
    helpText: "Subfolder name for daily/periodic notes.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["daily", "journal", "periodic", "vault", "System"],
    type: "string",
    writer: { kind: "endpoint", method: "PUT", path: "/watched-folders/{id}" },
  },
  {
    id: "knowledge.vault.templatesFolder",
    category: "knowledge",
    group: "vault",
    level: "advanced",
    label: "Templates folder",
    helpText: "Subfolder name for note templates. Contents are excluded from RAG retrieval.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["template", "vault", "System"],
    type: "string",
    writer: { kind: "endpoint", method: "PUT", path: "/watched-folders/{id}" },
  },
  {
    id: "knowledge.vault.attachmentsFolder",
    category: "knowledge",
    group: "vault",
    level: "advanced",
    label: "Attachments folder",
    helpText: "Subfolder name for file attachments (images, PDFs). Processed separately from markdown.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["attachments", "images", "files", "vault", "System"],
    type: "string",
    writer: { kind: "endpoint", method: "PUT", path: "/watched-folders/{id}" },
  },
  {
    id: "knowledge.vault.skipFolders",
    category: "knowledge",
    group: "vault",
    level: "advanced",
    label: "Skip folders",
    helpText: "Comma-separated subfolder names to exclude from ingestion (e.g. .trash, archive).",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["skip", "exclude", "ignore", "vault", "System"],
    type: "string",
    writer: { kind: "endpoint", method: "PUT", path: "/watched-folders/{id}" },
  },
  // ── Data Sources ───────────────────────────────────────────────────────────
  {
    id: "knowledge.sources.enable",
    category: "knowledge",
    group: "sources",
    level: "core",
    label: "Data sources",
    helpText: "Enable or disable individual knowledge sources (Wikipedia, arXiv, GitHub, etc.). Sources marked 'Needs key' require the corresponding API key env var.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["data source", "wikipedia", "arxiv", "github", "search", "web", "Governance", "System"],
    type: "boolean",
    writer: { kind: "endpoint", method: "POST", path: "/data-sources/{name}/enable" },
  },
  // ── Ingestion ─────────────────────────────────────────────────────────────
  {
    id: "knowledge.ingestion.storageMode",
    category: "knowledge",
    group: "ingestion",
    level: "core",
    label: "Storage mode",
    helpText: "\"Extract only\" stores text chunks and embeddings. \"Archive\" additionally keeps the original file bytes for later re-ingestion.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["storage", "archive", "extract", "Essentials", "Pipeline"],
    type: "enum",
    options: [
      { value: "extract_only", label: "Extract only", helpText: "Smaller footprint — only chunks and embeddings stored." },
      { value: "archive", label: "Archive", helpText: "Keeps original files for re-ingestion and audit." },
    ],
    default: "extract_only",
    writer: { kind: "settings-patch", key: "storage_mode" },
  },
  {
    id: "knowledge.ingestion.categorizeMode",
    category: "knowledge",
    group: "ingestion",
    level: "core",
    label: "Categorization mode",
    helpText: "How Cerid assigns documents to knowledge domains. \"Smart\" uses an LLM classifier. \"Pro\" enables multi-label classification across all domains simultaneously.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["categorize", "domain", "classify", "taxonomy", "Essentials", "Pipeline"],
    type: "enum",
    options: [
      { value: "manual", label: "Manual", helpText: "You assign domains at ingest time." },
      { value: "smart", label: "Smart", helpText: "LLM auto-assigns the most likely domain." },
      { value: "pro", label: "Pro — multi-label", helpText: "Classifies across all domains simultaneously." },
    ],
    default: "smart",
    entitlement: "pro",
    featureFlag: "custom_smart_rag",
    writer: { kind: "settings-patch", key: "categorize_mode" },
  },
  {
    id: "knowledge.ingestion.chunkSize",
    category: "knowledge",
    group: "ingestion",
    level: "advanced",
    label: "Chunk size",
    helpText: "Maximum tokens per chunk. Controlled by CHUNK_MAX_TOKENS in .env — restart required after change.",
    scopeOfEffect: { scope: "env", display: "Read-only here — set CHUNK_MAX_TOKENS in .env and restart." },
    keywords: ["chunk", "token", "size", "CHUNK_MAX_TOKENS", "Pipeline", "Essentials"],
    type: "display",
    writer: { kind: "env", envVar: "CHUNK_MAX_TOKENS" },
  },
  {
    id: "knowledge.ingestion.contextualChunks",
    category: "knowledge",
    group: "ingestion",
    level: "advanced",
    label: "Contextual chunks",
    helpText: "Generate a short LLM-written context sentence per chunk before embedding. Improves retrieval quality at the cost of extra ingestion time.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["contextual", "chunk", "embedding", "context", "Pipeline"],
    type: "boolean",
    default: false,
    writer: { kind: "settings-patch", key: "enable_contextual_chunks" },
  },
  // ── Briefs ─────────────────────────────────────────────────────────────────
  {
    id: "knowledge.briefs.writeToVault",
    category: "knowledge",
    group: "briefs",
    level: "core",
    label: "Write briefs to vault",
    helpText: "Auto-save generated briefs into a watched-folder vault. Requires a watched folder marked as a vault.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["briefs", "vault", "save", "auto-save", "System"],
    type: "boolean",
    default: false,
    writer: { kind: "endpoint", method: "PUT", path: "/briefs/settings" },
  },
  {
    id: "knowledge.briefs.targetVault",
    category: "knowledge",
    group: "briefs",
    level: "core",
    label: "Target vault",
    helpText: "Which watched folder (marked is_vault=true) should receive new briefs.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["briefs", "vault", "destination", "folder", "System"],
    type: "string",
    dependsOn: { id: "knowledge.briefs.writeToVault", equals: true },
    writer: { kind: "endpoint", method: "PUT", path: "/briefs/settings" },
  },
  {
    id: "knowledge.briefs.folderPrefix",
    category: "knowledge",
    group: "briefs",
    level: "advanced",
    label: "Folder prefix",
    helpText: "Subfolder path within the vault for new briefs. Default is \"_briefs\".",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["briefs", "prefix", "folder", "path", "System"],
    type: "string",
    default: "_briefs",
    dependsOn: { id: "knowledge.briefs.writeToVault", equals: true },
    writer: { kind: "endpoint", method: "PUT", path: "/briefs/settings" },
  },
  // ── Maintenance (relocated from System → Knowledge, ST12) ───────────────────
  {
    id: "knowledge.maintenance.rebuildIndexes",
    category: "knowledge",
    group: "maintenance",
    level: "core",
    label: "Rebuild indexes",
    helpText: "Rebuild BM25 keyword indexes for all domains. Takes ~1–5 minutes depending on corpus size. No data is deleted.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["rebuild", "index", "BM25", "maintenance", "System", "KB"],
    type: "action",
    writer: { kind: "endpoint", method: "POST", path: "/admin/kb/rebuild-index" },
  },
  {
    id: "knowledge.maintenance.rescore",
    category: "knowledge",
    group: "maintenance",
    level: "core",
    label: "Rescore all",
    helpText: "Re-compute quality scores for all artifacts. Takes ~2–10 minutes. Improves retrieval ranking accuracy but does not change stored content.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["rescore", "quality", "score", "maintenance", "System", "KB"],
    type: "action",
    writer: { kind: "endpoint", method: "POST", path: "/admin/kb/rescore" },
  },
  {
    id: "knowledge.maintenance.regenerateSummaries",
    category: "knowledge",
    group: "maintenance",
    level: "core",
    label: "Regenerate summaries",
    helpText: "Re-run LLM synopsis generation for all artifacts. Takes ~5–20 minutes depending on corpus size and provider speed.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["regenerate", "summary", "synopsis", "maintenance", "System", "KB"],
    type: "action",
    writer: { kind: "endpoint", method: "POST", path: "/admin/kb/regenerate-summaries" },
  },
  {
    id: "knowledge.maintenance.clearDomain",
    category: "knowledge",
    group: "maintenance",
    level: "core",
    label: "Clear domain",
    helpText: "Permanently delete all chunks, embeddings, and artifacts in a knowledge domain. This cannot be undone. Type the domain name to confirm.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["clear", "delete", "domain", "wipe", "danger", "maintenance", "System", "KB"],
    type: "action",
    danger: "type-to-confirm",
    writer: { kind: "endpoint", method: "POST", path: "/admin/kb/clear-domain/{domain}" },
  },
]
