// Copyright (c) 2026 Cerid AI. All rights reserved.
// SPDX-License-Identifier: FSL-1.1-ALv2

import type { SettingDef } from "./types"

const SERVER = { scope: "server" as const, display: "Global for this server — all sessions and users." }
const DEVICE = { scope: "device" as const, display: "This device only — stored in your browser." }
const ENV = { scope: "env" as const, display: "Deployment-time only — set via .env and restart the server." }

export const MODELS_DEFS: SettingDef[] = [
  // ── Providers group ────────────────────────────────────────────────────────
  {
    id: "models.providers.openrouterKey",
    category: "models",
    group: "providers",
    level: "core",
    label: "OpenRouter API Key",
    helpText: "API key for OpenRouter cloud inference. Stored server-side; the raw value never round-trips to the browser.",
    scopeOfEffect: SERVER,
    keywords: ["Essentials", "key", "cloud", "API", "credentials", "openrouter"],
    type: "string",
    writer: { kind: "endpoint", method: "PUT", path: "/settings/openrouter-key" },
  },
  {
    id: "models.providers.openrouterStatus",
    category: "models",
    group: "providers",
    level: "core",
    label: "Provider Status",
    helpText: "Live connectivity status for OpenRouter, OpenAI, Anthropic, xAI, and Ollama. Fix paths shown inline when a provider is unreachable.",
    scopeOfEffect: ENV,
    keywords: ["Essentials", "connection", "status", "health", "provider", "openrouter", "openai", "anthropic"],
    type: "display",
    writer: { kind: "env", envVar: "OPENROUTER_API_KEY" },
  },

  // ── Pipeline tasks group ───────────────────────────────────────────────────
  {
    id: "models.pipelineTasks.provider",
    category: "models",
    group: "pipelineTasks",
    level: "core",
    label: "Pipeline task provider",
    helpText: "Where internal pipeline LLM calls run: ingest enrichment, LLM-rerank, memory extraction, claim extraction, and verification. Switching takes effect immediately — no restart required.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "Essentials", "internal_llm_provider", "routing", "ollama", "openrouter", "quenchforge", "inference backend"],
    type: "enum",
    options: [
      { value: "openrouter", label: "OpenRouter (cloud)", helpText: "Default. Routes to the best available free/cheap model." },
      { value: "ollama", label: "Ollama (local)", helpText: "Uses the Ollama-protocol daemon on OLLAMA_URL." },
      { value: "quenchforge", label: "Quenchforge (local GPU)", helpText: "AMD/Intel Mac GPU acceleration via the Quenchforge gateway." },
    ],
    default: "openrouter",
    writer: { kind: "settings-patch", key: "internal_llm_provider" },
  },
  {
    id: "models.pipelineTasks.model",
    category: "models",
    group: "pipelineTasks",
    level: "core",
    label: "Pipeline task model",
    helpText: "Model name sent to the pipeline task provider. Leave empty to use the provider's default (Ollama: OLLAMA_DEFAULT_MODEL; OpenRouter: meta-llama/llama-3.3-70b-instruct:free).",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "internal_llm_model", "model", "pipeline tasks", "llama"],
    type: "string",
    default: "",
    writer: { kind: "settings-patch", key: "internal_llm_model" },
  },
  {
    id: "models.pipelineTasks.embeddingsProvider",
    category: "models",
    group: "pipelineTasks",
    level: "advanced",
    label: "Embeddings provider",
    helpText: "Where dense-vector embeddings are computed. 'Sidecar' auto-detects CoreML/CUDA on ARM/Linux; 'Quenchforge' opts in to AMD GPU acceleration; 'In-process' uses CPU.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "embeddings_provider", "embed", "sidecar", "quenchforge", "GPU"],
    type: "enum",
    options: [
      { value: "sidecar", label: "Sidecar (auto)", helpText: "Picks CoreML on Apple Silicon, CUDA on Linux GPU, CPU otherwise." },
      { value: "quenchforge", label: "Quenchforge (AMD GPU)", helpText: "For AMD Mac (Vega II / RX) hardware." },
      { value: "in-process", label: "In-process (CPU)", helpText: "Runs in the FastAPI process. Slow for large corpora." },
    ],
    default: "sidecar",
    writer: { kind: "settings-patch", key: "embeddings_provider" },
  },
  {
    id: "models.pipelineTasks.embedModel",
    category: "models",
    group: "pipelineTasks",
    level: "advanced",
    label: "Quenchforge embed model",
    helpText: "GGUF model name Quenchforge serves for embeddings. Must produce 768-dim vectors to match ChromaDB. Only relevant when embeddings provider is set to Quenchforge.",
    scopeOfEffect: ENV,
    keywords: ["Pipeline", "QUENCHFORGE_EMBED_MODEL", "embedding model", "768"],
    type: "display",
    writer: { kind: "env", envVar: "QUENCHFORGE_EMBED_MODEL" },
    visibleWhen: (ctx) => ctx.serverSettings?.embeddings_provider === "quenchforge",
  },
  {
    id: "models.pipelineTasks.rerankProvider",
    category: "models",
    group: "pipelineTasks",
    level: "advanced",
    label: "Rerank provider",
    helpText: "Where the cross-encoder reranker runs. Same provider options as embeddings.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "rerank_provider", "reranker", "sidecar", "quenchforge", "GPU"],
    type: "enum",
    options: [
      { value: "sidecar", label: "Sidecar (auto)" },
      { value: "quenchforge", label: "Quenchforge (AMD GPU)" },
      { value: "in-process", label: "In-process (CPU)" },
    ],
    default: "sidecar",
    writer: { kind: "settings-patch", key: "rerank_provider" },
  },
  {
    id: "models.pipelineTasks.rerankModel",
    category: "models",
    group: "pipelineTasks",
    level: "advanced",
    label: "Quenchforge rerank model",
    helpText: "GGUF reranker model Quenchforge serves. BGE Reranker v2 m3 is the recommended default.",
    scopeOfEffect: ENV,
    keywords: ["Pipeline", "QUENCHFORGE_RERANK_MODEL", "reranker model", "bge"],
    type: "display",
    writer: { kind: "env", envVar: "QUENCHFORGE_RERANK_MODEL" },
    visibleWhen: (ctx) => ctx.serverSettings?.rerank_provider === "quenchforge",
  },

  // ── Routing group ──────────────────────────────────────────────────────────
  {
    id: "models.routing.mode",
    category: "models",
    group: "routing",
    level: "core",
    label: "Model routing",
    helpText: "How Cerid selects the chat model per message. Manual: always use the assigned model. Recommend: automatically suggest a better model for complex queries. Auto: switch models automatically without asking.",
    scopeOfEffect: DEVICE,
    keywords: ["Essentials", "Pipeline", "routing", "model router", "auto", "smart routing"],
    type: "enum",
    options: [
      { value: "manual", label: "Manual", helpText: "Always uses the current assigned model." },
      { value: "recommend", label: "Recommend", helpText: "Suggests a better model for complex tasks." },
      { value: "auto", label: "Auto", helpText: "Switches automatically without confirmation." },
    ],
    default: "manual",
    writer: { kind: "preferences", key: "routing_mode" },
    writtenBy: "chat toolbar",
    mirrors: ["chat-toolbar"],
  },
  {
    id: "models.routing.costSensitivity",
    category: "models",
    group: "routing",
    level: "core",
    label: "Cost sensitivity",
    helpText: "How strongly the model router favors cheaper models when routing. High = always pick the cheapest model that can handle the task.",
    scopeOfEffect: SERVER,
    keywords: ["Essentials", "Pipeline", "cost", "cost_sensitivity", "budget", "cheap", "expensive"],
    type: "enum",
    options: [
      { value: "low", label: "Low — prefer quality" },
      { value: "medium", label: "Medium — balance" },
      { value: "high", label: "High — prefer cost savings" },
    ],
    default: "medium",
    writer: { kind: "settings-patch", key: "cost_sensitivity" },
  },

  // ── Local inference group ──────────────────────────────────────────────────
  {
    id: "models.localInference.ollamaStatus",
    category: "models",
    group: "localInference",
    level: "core",
    label: "Ollama / Quenchforge",
    helpText: "Status and setup wizard for the local inference daemon. Ollama and Quenchforge both speak the same wire protocol; Quenchforge adds AMD/Intel Mac GPU acceleration.",
    scopeOfEffect: ENV,
    keywords: ["System", "Ollama", "quenchforge", "local LLM", "inference", "GPU", "setup wizard", "install"],
    type: "display",
    writer: { kind: "env", envVar: "OLLAMA_URL" },
  },
  {
    id: "models.localInference.inferenceTier",
    category: "models",
    group: "localInference",
    level: "core",
    label: "Inference tier",
    helpText: "Detected inference capability level — indicates whether GPU acceleration is active and which hardware path is being used.",
    scopeOfEffect: ENV,
    keywords: ["System", "inference tier", "GPU", "acceleration", "hardware"],
    type: "display",
    writer: { kind: "env", envVar: "INFERENCE_MODE" },
  },
  {
    id: "models.localInference.endpoint",
    category: "models",
    group: "localInference",
    level: "advanced",
    label: "Local inference endpoint",
    helpText: "URL of the running Ollama or Quenchforge daemon. Used for model listing, pulling, and pipeline routing.",
    scopeOfEffect: ENV,
    keywords: ["System", "OLLAMA_URL", "QUENCHFORGE_URL", "endpoint", "local", "localhost:11434"],
    type: "display",
    writer: { kind: "env", envVar: "OLLAMA_URL" },
  },

  // ── Model catalog group ────────────────────────────────────────────────────
  {
    id: "models.catalog.updates",
    category: "models",
    group: "catalog",
    level: "advanced",
    label: "Model updates",
    helpText: "Track new, deprecated, and price-changed models in the OpenRouter catalog. Dismiss alerts once you've reviewed them.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "model management", "updates", "catalog", "deprecated", "new models"],
    type: "display",
    writer: { kind: "endpoint", method: "POST", path: "/models/updates/check" },
  },
  {
    id: "models.catalog.compatDoctor",
    category: "models",
    group: "catalog",
    level: "advanced",
    label: "Compatibility check",
    helpText: "Verifies that configured models are compatible with your hardware profile. Reports errors, warnings, and info-level findings.",
    scopeOfEffect: ENV,
    keywords: ["Pipeline", "model compatibility", "hardware", "compat doctor", "hardware unset", "CERID_HARDWARE_PROFILE"],
    type: "display",
    writer: { kind: "env", envVar: "CERID_HARDWARE_PROFILE" },
  },

  // ── Model cache group ──────────────────────────────────────────────────────
  {
    id: "models.cache.inferenceModels",
    category: "models",
    group: "cache",
    level: "advanced",
    label: "Inference model cache",
    helpText: "Reranker and embedder ONNX models cached locally for fast startup. Warm the cache now to avoid a delay on your first semantic search.",
    scopeOfEffect: SERVER,
    keywords: ["System", "inference models", "ONNX", "reranker", "embedder", "preload", "cache", "CERID_PRELOAD_MODELS"],
    type: "action",
    writer: { kind: "endpoint", method: "POST", path: "/setup/models/preload" },
  },

  // ── Speech-to-text group ───────────────────────────────────────────────────
  {
    id: "models.speechToText.manager",
    category: "models",
    group: "speechToText",
    level: "core",
    label: "Manage speech-to-text models",
    helpText: "Download and manage Whisper speech-to-text models. Higher quality = slower and larger file. Cached at ~/.cerid/models/whisper/.",
    scopeOfEffect: ENV,
    keywords: ["System", "Whisper", "speech-to-text", "transcription", "audio", "download", "voice"],
    type: "display",
    writer: { kind: "env", envVar: "WHISPER_MODEL" },
  },
]
