// Copyright (c) 2026 Cerid AI. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import type { SettingDef } from "./types"

const SERVER = { scope: "server" as const, display: "Global for this server — all sessions and users." }
const ENV = { scope: "env" as const, display: "Deployment-time only — set via .env and restart the server." }

export const RETRIEVAL_DEFS: SettingDef[] = [
  // ── Profile group ──────────────────────────────────────────────────────────
  {
    id: "retrieval.profile.preset",
    category: "retrieval",
    group: "profile",
    level: "core",
    label: "Retrieval profile",
    helpText: "Apply a preset bundle of retrieval settings. Balanced is the recommended starting point. A 'Custom' badge appears when your manual edits diverge from all presets.",
    scopeOfEffect: SERVER,
    keywords: ["Essentials", "Pipeline", "Response tier", "preset", "profile", "balanced", "thorough", "speed"],
    type: "enum",
    options: [
      { value: "balanced", label: "Balanced", helpText: "Sensible defaults for most knowledge bases." },
      { value: "thorough", label: "Thorough", helpText: "Higher recall at the cost of latency. Pro only." },
      { value: "speed", label: "Speed", helpText: "Minimal pipeline for fast answers on small corpora." },
    ],
    default: "balanced",
    writer: { kind: "settings-patch", key: "rag_mode" },
  },

  // ── Context injection group ────────────────────────────────────────────────
  {
    id: "retrieval.contextInjection.autoInject",
    category: "retrieval",
    group: "contextInjection",
    level: "core",
    label: "Auto-inject KB context",
    helpText: "Automatically retrieves relevant documents from your knowledge base and injects them into each message when confidence exceeds the threshold.",
    scopeOfEffect: SERVER,
    keywords: ["Essentials", "auto inject", "enable_auto_inject", "KB", "context", "retrieval"],
    type: "boolean",
    default: true,
    writer: { kind: "settings-patch", key: "enable_auto_inject" },
    writtenBy: "chat toolbar",
    mirrors: ["chat-toolbar"],
  },
  {
    id: "retrieval.contextInjection.threshold",
    category: "retrieval",
    group: "contextInjection",
    level: "core",
    label: "Injection threshold",
    helpText: "How close to the best match a document must score to be auto-injected, as a fraction of the top hit (0–1). Relevance scores are ordinal, so this is relative to the strongest result, not an absolute cutoff. Lower = more context injected; higher = only near-top matches.",
    scopeOfEffect: SERVER,
    keywords: ["Essentials", "auto_inject_threshold", "threshold", "relevance", "confidence"],
    type: "number",
    default: 0.15,
    writer: { kind: "settings-patch", key: "auto_inject_threshold" },
    dependsOn: { id: "retrieval.contextInjection.autoInject", equals: true },
    writtenBy: "chat toolbar",
    mirrors: ["chat-toolbar"],
  },
  {
    id: "retrieval.contextInjection.ragMode",
    category: "retrieval",
    group: "contextInjection",
    level: "core",
    label: "Injection mode",
    helpText: "Controls when context is injected. Smart: injects when the query looks like it needs knowledge. Always: injects on every message. Off: no automatic injection (use @mentions).",
    scopeOfEffect: SERVER,
    keywords: ["Essentials", "rag_mode", "RAG mode", "KB injection mode", "smart", "always", "off", "manual", "Pipeline"],
    type: "enum",
    options: [
      { value: "smart", label: "Smart", helpText: "Injects only when the query appears to need knowledge." },
      { value: "always", label: "Always", helpText: "Injects context into every message." },
      { value: "off", label: "Off", helpText: "No automatic injection — use @mentions to include documents manually." },
    ],
    default: "smart",
    writer: { kind: "settings-patch", key: "rag_mode" },
    writtenBy: "chat toolbar",
    mirrors: ["chat-toolbar"],
  },

  // ── Answer quality group ───────────────────────────────────────────────────
  {
    id: "retrieval.answerQuality.selfRag",
    category: "retrieval",
    group: "answerQuality",
    level: "core",
    label: "Self-RAG validation",
    helpText: "Re-retrieves and re-scores evidence after the first answer draft to catch gaps. Adds 200–400ms per response.",
    scopeOfEffect: SERVER,
    keywords: ["Essentials", "enable_self_rag", "self-RAG", "validation", "retrieval refinement"],
    type: "boolean",
    default: true,
    writer: { kind: "settings-patch", key: "enable_self_rag" },
  },
  {
    id: "retrieval.answerQuality.hallucinationCheck",
    category: "retrieval",
    group: "answerQuality",
    level: "core",
    label: "Hallucination check",
    helpText: "Runs NLI entailment scoring against retrieved sources after each response. Flags claims not supported by your knowledge base.",
    scopeOfEffect: SERVER,
    keywords: ["Essentials", "enable_hallucination_check", "hallucination", "NLI", "fact check", "verification"],
    type: "boolean",
    default: true,
    writer: { kind: "settings-patch", key: "enable_hallucination_check" },
    writtenBy: "Feedback Loop preset",
    mirrors: ["chat-toolbar"],
  },
  {
    id: "retrieval.answerQuality.hallucinationThreshold",
    category: "retrieval",
    group: "answerQuality",
    level: "advanced",
    label: "Hallucination confidence threshold",
    helpText: "Minimum NLI entailment score (0–1) needed to flag a claim as potentially hallucinated. Higher = only flag highly unsupported claims.",
    scopeOfEffect: SERVER,
    keywords: ["Essentials", "hallucination_threshold", "threshold", "NLI", "confidence", "entailment"],
    type: "number",
    default: 0.7,
    writer: { kind: "settings-patch", key: "hallucination_threshold" },
    dependsOn: { id: "retrieval.answerQuality.hallucinationCheck", equals: true },
  },

  // ── Learning group ─────────────────────────────────────────────────────────
  {
    id: "retrieval.learning.feedbackLoop",
    category: "retrieval",
    group: "learning",
    level: "core",
    label: "Feedback loop",
    helpText: "Tracks which retrieved documents were useful (via thumbs up/down) to improve future retrieval ranking over time.",
    scopeOfEffect: SERVER,
    keywords: ["Essentials", "enable_feedback_loop", "feedback", "learning", "ranking improvement"],
    type: "boolean",
    default: true,
    writer: { kind: "settings-patch", key: "enable_feedback_loop" },
    writtenBy: "Response preset, chat toolbar",
    mirrors: ["chat-toolbar"],
  },
  {
    id: "retrieval.learning.memoryExtraction",
    category: "retrieval",
    group: "learning",
    level: "core",
    label: "Memory extraction",
    helpText: "Extracts facts, preferences, and decisions from conversations and stores them in episodic memory for later retrieval.",
    scopeOfEffect: SERVER,
    keywords: ["Essentials", "enable_memory_extraction", "memory", "episodic", "extraction", "learning"],
    type: "boolean",
    default: true,
    writer: { kind: "settings-patch", key: "enable_memory_extraction" },
    writtenBy: "Response preset, chat toolbar",
    mirrors: ["chat-toolbar"],
  },

  // ── Hybrid weights group ───────────────────────────────────────────────────
  {
    id: "retrieval.hybridWeights.vectorWeight",
    category: "retrieval",
    group: "hybridWeights",
    level: "advanced",
    label: "Vector weight",
    helpText: "Relative weight of semantic vector similarity in hybrid search. Use together with keyword weight — both near zero will yield very few results.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "hybrid_vector_weight", "vector", "semantic", "weight", "search weights"],
    type: "number",
    default: 0.5,
    writer: { kind: "settings-patch", key: "hybrid_vector_weight" },
  },
  {
    id: "retrieval.hybridWeights.keywordWeight",
    category: "retrieval",
    group: "hybridWeights",
    level: "advanced",
    label: "Keyword weight",
    helpText: "Relative weight of BM25 keyword matching in hybrid search. Pairs with vector weight.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "hybrid_keyword_weight", "keyword", "BM25", "weight", "search weights"],
    type: "number",
    default: 0.5,
    writer: { kind: "settings-patch", key: "hybrid_keyword_weight" },
  },
  {
    id: "retrieval.hybridWeights.rerankLlmWeight",
    category: "retrieval",
    group: "hybridWeights",
    level: "advanced",
    label: "Rerank LLM weight",
    helpText: "Weight given to the LLM reranker score when blending with the original relevance score.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "rerank_llm_weight", "rerank", "LLM weight"],
    type: "number",
    default: 0.5,
    writer: { kind: "settings-patch", key: "rerank_llm_weight" },
  },
  {
    id: "retrieval.hybridWeights.rerankOriginalWeight",
    category: "retrieval",
    group: "hybridWeights",
    level: "advanced",
    label: "Rerank original weight",
    helpText: "Weight given to the original relevance score when blending with the LLM reranker score.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "rerank_original_weight", "rerank", "original weight"],
    type: "number",
    default: 0.5,
    writer: { kind: "settings-patch", key: "rerank_original_weight" },
  },
  {
    id: "retrieval.hybridWeights.packRelevanceWeight",
    category: "retrieval",
    group: "hybridWeights",
    level: "advanced",
    label: "Knowledge-pack weight",
    helpText: "Multiplier applied to knowledge-pack results after reranking. Below 1.0 makes your own data win ties; 1.0 is neutral (personal-first).",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "pack_relevance_weight", "knowledge packs", "personal-first"],
    type: "number",
    default: 0.7,
    writer: { kind: "settings-patch", key: "pack_relevance_weight" },
  },
  {
    id: "retrieval.hybridWeights.temporalHalfLife",
    category: "retrieval",
    group: "hybridWeights",
    level: "advanced",
    label: "Temporal half-life",
    helpText: "Number of days after which a document's recency score decays to half. Controlled by TEMPORAL_HALF_LIFE_DAYS in .env.",
    scopeOfEffect: ENV,
    keywords: ["Pipeline", "temporal_half_life_days", "TEMPORAL_HALF_LIFE_DAYS", "recency", "decay", "time"],
    type: "display",
    writer: { kind: "env", envVar: "TEMPORAL_HALF_LIFE_DAYS" },
  },
  {
    id: "retrieval.hybridWeights.recencyWeight",
    category: "retrieval",
    group: "hybridWeights",
    level: "advanced",
    label: "Recency weight",
    helpText: "How strongly document recency influences ranking. Controlled by TEMPORAL_RECENCY_WEIGHT in .env.",
    scopeOfEffect: ENV,
    keywords: ["Pipeline", "temporal_recency_weight", "TEMPORAL_RECENCY_WEIGHT", "recency", "time"],
    type: "display",
    writer: { kind: "env", envVar: "TEMPORAL_RECENCY_WEIGHT" },
  },

  // ── Smart RAG group ────────────────────────────────────────────────────────
  {
    id: "retrieval.smartRag.weights",
    category: "retrieval",
    group: "smartRag",
    level: "advanced",
    label: "Custom Smart RAG",
    helpText: "Fine-tune per-source retrieval weights to boost or demote specific knowledge domains. Weights range from 0.0 (demote) to 2.0 (boost). Pro feature — requires custom_smart_rag flag.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "smart RAG", "custom_smart_rag", "rag weights", "per-source", "retrieval weights", "Pro"],
    type: "action",
    writer: { kind: "endpoint", method: "PUT", path: "/settings/rag/weights" },
    entitlement: "pro",
    featureFlag: "custom_smart_rag",
  },
  {
    id: "retrieval.smartRag.reset",
    category: "retrieval",
    group: "smartRag",
    level: "advanced",
    label: "Reset Smart RAG weights",
    helpText: "Resets all per-source weights to the default (1.0), removing any custom boosts or demotions.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "smart RAG", "reset weights", "custom_smart_rag"],
    type: "action",
    danger: "confirm",
    writer: { kind: "endpoint", method: "DELETE", path: "/settings/rag/weights" },
    entitlement: "pro",
    featureFlag: "custom_smart_rag",
  },

  // ── Pipeline stages group ──────────────────────────────────────────────────
  {
    id: "retrieval.pipelineStages.adaptiveRetrieval",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Adaptive retrieval",
    helpText: "Skips or reduces retrieval for simple queries (greetings, arithmetic, follow-ups) to reduce latency. Complex queries get full retrieval.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "enable_adaptive_retrieval", "adaptive", "skip retrieval", "fast path"],
    type: "boolean",
    default: true,
    writer: { kind: "settings-patch", key: "enable_adaptive_retrieval" },
  },
  {
    id: "retrieval.pipelineStages.adaptiveLightTopK",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Adaptive light top-K",
    helpText: "Number of results to fetch when adaptive retrieval determines a query is 'light'. Smaller = faster for simple questions.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "adaptive_retrieval_light_top_k", "top-k", "adaptive", "light"],
    type: "number",
    default: 3,
    writer: { kind: "settings-patch", key: "adaptive_retrieval_light_top_k" },
    dependsOn: { id: "retrieval.pipelineStages.adaptiveRetrieval", equals: true },
  },
  {
    id: "retrieval.pipelineStages.sparseRetrieval",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Sparse retrieval (SPLADE-v3)",
    helpText: "Adds a learned sparse retriever (SPLADE-v3) alongside vector and BM25. Enabling this automatically sets fusion mode to tri-RRF. Disabling restores the previous fusion mode.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "enable_sparse_retrieval", "SPLADE", "sparse", "tri-RRF", "fusion"],
    type: "boolean",
    default: false,
    writer: { kind: "settings-patch", key: "enable_sparse_retrieval" },
  },
  {
    id: "retrieval.pipelineStages.fusionMode",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Fusion mode",
    helpText: "How results from multiple retrievers are combined. weighted_sum: legacy. rrf: Reciprocal Rank Fusion (vector + BM25). tri_rrf: RRF with SPLADE-v3 as the third retriever.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "hybrid_fusion_mode", "fusion", "RRF", "tri-RRF", "weighted sum"],
    type: "enum",
    options: [
      { value: "weighted_sum", label: "Weighted sum", helpText: "Legacy — direct score blending." },
      { value: "rrf", label: "RRF (vector + BM25)", helpText: "Reciprocal Rank Fusion, two retrievers." },
      { value: "tri_rrf", label: "Tri-RRF (+ SPLADE)", helpText: "RRF with three retrievers. Auto-set when sparse is enabled." },
    ],
    default: "weighted_sum",
    writer: { kind: "settings-patch", key: "hybrid_fusion_mode" },
  },
  {
    id: "retrieval.pipelineStages.sparseWeight",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Sparse retriever weight",
    helpText: "Per-retriever weight for SPLADE-v3 in tri-RRF fusion. Range 0–5.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "hybrid_rrf_sparse_weight", "sparse weight", "SPLADE", "tri-RRF"],
    type: "number",
    default: 1.0,
    writer: { kind: "settings-patch", key: "hybrid_rrf_sparse_weight" },
    dependsOn: { id: "retrieval.pipelineStages.sparseRetrieval", equals: true },
  },
  {
    id: "retrieval.pipelineStages.queryDecomposition",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Query decomposition",
    helpText: "Breaks complex queries into parallel sub-queries for broader coverage. Each sub-query runs independently and results are merged.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "enable_query_decomposition", "sub-query", "decomposition", "multi-query"],
    type: "boolean",
    default: false,
    writer: { kind: "settings-patch", key: "enable_query_decomposition" },
  },
  {
    id: "retrieval.pipelineStages.maxSubqueries",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Max sub-queries",
    helpText: "Maximum number of sub-queries generated when query decomposition is active.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "query_decomposition_max_subqueries", "sub-queries", "decomposition count"],
    type: "number",
    default: 4,
    writer: { kind: "settings-patch", key: "query_decomposition_max_subqueries" },
    dependsOn: { id: "retrieval.pipelineStages.queryDecomposition", equals: true },
  },
  {
    id: "retrieval.pipelineStages.mmrDiversity",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Diversity reordering (MMR)",
    helpText: "Reorders results using Maximal Marginal Relevance to reduce redundancy. Useful when multiple chunks cover the same passage.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "enable_mmr_diversity", "MMR", "diversity", "redundancy", "reorder"],
    type: "boolean",
    default: false,
    writer: { kind: "settings-patch", key: "enable_mmr_diversity" },
  },
  {
    id: "retrieval.pipelineStages.mmrLambda",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Diversity balance (λ)",
    helpText: "MMR trade-off between relevance (1.0) and diversity (0.0). 0.5 balances both equally.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "mmr_lambda", "lambda", "MMR", "diversity balance"],
    type: "number",
    default: 0.5,
    writer: { kind: "settings-patch", key: "mmr_lambda" },
    dependsOn: { id: "retrieval.pipelineStages.mmrDiversity", equals: true },
  },
  {
    id: "retrieval.pipelineStages.intelligentAssembly",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Intelligent assembly",
    helpText: "Three-pass context assembly that tries to cover multiple answer facets. Reduces redundant context; adds ~100ms.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "enable_intelligent_assembly", "assembly", "context", "facets"],
    type: "boolean",
    default: false,
    writer: { kind: "settings-patch", key: "enable_intelligent_assembly" },
  },
  {
    id: "retrieval.pipelineStages.lateInteraction",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Late interaction scoring",
    helpText: "ColBERT-inspired token-level scoring applied to top candidates for fine-grained relevance. Adds latency proportional to top-N.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "enable_late_interaction", "ColBERT", "late interaction", "token scoring"],
    type: "boolean",
    default: false,
    writer: { kind: "settings-patch", key: "enable_late_interaction" },
  },
  {
    id: "retrieval.pipelineStages.lateInteractionTopN",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Late interaction candidates",
    helpText: "Number of top candidates re-scored by the late interaction model.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "late_interaction_top_n", "top-N", "late interaction", "candidates"],
    type: "number",
    default: 8,
    writer: { kind: "settings-patch", key: "late_interaction_top_n" },
    dependsOn: { id: "retrieval.pipelineStages.lateInteraction", equals: true },
  },
  {
    id: "retrieval.pipelineStages.lateInteractionBlend",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Late interaction blend weight",
    helpText: "How much the late-interaction score contributes to the final ranking (0–0.5). 0 = disabled even when toggle is on.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "late_interaction_blend_weight", "blend", "late interaction"],
    type: "number",
    default: 0.2,
    writer: { kind: "settings-patch", key: "late_interaction_blend_weight" },
    dependsOn: { id: "retrieval.pipelineStages.lateInteraction", equals: true },
  },
  {
    id: "retrieval.pipelineStages.semanticCache",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Semantic query cache",
    helpText: "Caches answers to semantically similar queries to speed up repeat questions. Cache is session-scoped.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "enable_semantic_cache", "cache", "semantic cache", "speed"],
    type: "boolean",
    default: true,
    writer: { kind: "settings-patch", key: "enable_semantic_cache" },
  },
  {
    id: "retrieval.pipelineStages.semanticCacheThreshold",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Cache similarity threshold",
    helpText: "Minimum similarity score (0.5–1.0) for a cached answer to be considered a hit. Higher = stricter matching.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "semantic_cache_threshold", "cache threshold", "similarity"],
    type: "number",
    default: 0.92,
    writer: { kind: "settings-patch", key: "semantic_cache_threshold" },
    dependsOn: { id: "retrieval.pipelineStages.semanticCache", equals: true },
  },
  {
    id: "retrieval.pipelineStages.memoryConsolidation",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Memory consolidation",
    helpText: "Deduplicates and merges similar episodic memories during extraction to prevent the memory store from growing unboundedly.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "enable_memory_consolidation", "memory", "dedup", "consolidation"],
    type: "boolean",
    default: false,
    writer: { kind: "settings-patch", key: "enable_memory_consolidation" },
  },
  {
    id: "retrieval.pipelineStages.contextCompression",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Context compression",
    helpText: "LLM-based summarization of conversation context to stay within model token limits. Adds latency on long sessions.",
    scopeOfEffect: SERVER,
    keywords: ["Pipeline", "enable_context_compression", "context compression", "token limit", "summarize"],
    type: "boolean",
    default: false,
    writer: { kind: "settings-patch", key: "enable_context_compression" },
  },
  {
    id: "retrieval.pipelineStages.contextualChunks",
    category: "retrieval",
    group: "pipelineStages",
    level: "advanced",
    label: "Contextual chunks",
    helpText: "Prepends an LLM-generated situational summary to each chunk before embedding, improving retrieval quality for ambiguous queries. Doubles ingest cost.",
    scopeOfEffect: SERVER,
    keywords: ["Essentials", "Knowledge", "enable_contextual_chunks", "contextual chunking", "situational summary"],
    type: "boolean",
    default: false,
    writer: { kind: "settings-patch", key: "enable_contextual_chunks" },
  },
]
