// Copyright (c) 2026 Cerid AI. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import type { SettingDef } from "./types"

export const SYSTEM_DEFS: SettingDef[] = [
  // ── Server Info ────────────────────────────────────────────────────────────
  {
    id: "system.server.version",
    category: "system",
    group: "server",
    level: "core",
    label: "Server version",
    helpText: "The running Cerid AI server version. Used for support and update reference.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["version", "server", "build", "release"],
    type: "display",
    writer: { kind: "readonly", endpoint: "/settings" },
  },
  {
    id: "system.server.machineId",
    category: "system",
    group: "server",
    level: "core",
    label: "Machine ID",
    helpText: "Stable identifier for this server instance. Used for sync conflict resolution and license seat binding.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["machine ID", "instance", "identifier", "System"],
    type: "display",
    writer: { kind: "readonly", endpoint: "/settings" },
  },
  {
    id: "system.server.featureTier",
    category: "system",
    group: "server",
    level: "core",
    label: "Feature tier",
    helpText: "The active feature tier reported by the server. Controlled by CERID_TIER in .env (overrides the license key at deploy time for dev/enterprise use).",
    scopeOfEffect: {
      scope: "env",
      display: "Read-only here — set CERID_TIER in .env or activate a license key on Plan & Billing.",
    },
    keywords: ["tier", "feature", "CERID_TIER", "plan", "pro", "enterprise", "System"],
    type: "display",
    writer: { kind: "env", envVar: "CERID_TIER" },
  },
  // ── Platform Capabilities ──────────────────────────────────────────────────
  {
    id: "system.capabilities.platform",
    category: "system",
    group: "capabilities",
    level: "core",
    label: "Platform capabilities",
    helpText: "Hardware and software capabilities detected on this server: GPU type, Metal/CUDA support, installed optional services.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["platform", "capabilities", "hardware", "GPU", "metal", "CUDA", "System"],
    type: "display",
    writer: { kind: "readonly", endpoint: "/settings" },
  },
  // ── Storage ────────────────────────────────────────────────────────────────
  {
    id: "system.storage.usage",
    category: "system",
    group: "storage",
    level: "core",
    label: "Storage usage",
    helpText: "Disk and memory usage across ChromaDB (vectors), Neo4j (graph), Redis (state), and BM25 (keyword index). Refreshed every 60 seconds.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["storage", "disk", "memory", "usage", "chroma", "neo4j", "redis", "bm25", "System"],
    type: "display",
    writer: { kind: "readonly", endpoint: "/system/storage" },
  },
  // ── Sync ──────────────────────────────────────────────────────────────────
  {
    id: "system.sync.conflictStrategy",
    category: "system",
    group: "sync",
    level: "core",
    label: "Import conflict strategy",
    helpText: "When importing a sync archive that conflicts with local data: \"Remote wins\" replaces local. \"Local wins\" keeps local. \"Merge\" attempts field-level reconciliation.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["sync", "conflict", "strategy", "import", "merge", "local", "remote", "System"],
    type: "enum",
    options: [
      { value: "remote_wins", label: "Remote wins", helpText: "Incoming data overwrites local." },
      { value: "local_wins", label: "Local wins", helpText: "Local data is kept; incoming discarded." },
      { value: "merge", label: "Merge", helpText: "Field-level merge; conflicts flagged." },
    ],
    default: "remote_wins",
    writer: { kind: "local", storageKey: "cerid-sync-conflict-strategy" },
  },
  {
    id: "system.sync.export",
    category: "system",
    group: "sync",
    level: "core",
    label: "Export knowledge base",
    helpText: "Export the current KB to the configured sync directory as a portable archive.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["export", "sync", "backup", "archive", "System"],
    type: "action",
    writer: { kind: "endpoint", method: "POST", path: "/sync/export" },
  },
  {
    id: "system.sync.import",
    category: "system",
    group: "sync",
    level: "core",
    label: "Import knowledge base",
    helpText: "Import a sync archive into the local KB. Applies the conflict strategy selected above. This may overwrite local data.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["import", "sync", "restore", "archive", "System"],
    type: "action",
    danger: "confirm",
    writer: { kind: "endpoint", method: "POST", path: "/sync/import" },
  },
  // ── Backup ─────────────────────────────────────────────────────────────────
  {
    id: "system.sync.backup",
    category: "system",
    group: "sync",
    level: "core",
    label: "Full backup export",
    helpText: "Runs a full export (bypassing the incremental since-cursor) to the sync directory, covering every store: Neo4j artifacts/domains/relationships/memories/entities, ChromaDB chunks, and the Redis audit log. Pair with scripts/cerid-backup.sh for a portable archive.",
    scopeOfEffect: { scope: "server", display: "Applies to this server instance — all sessions." },
    keywords: ["backup", "full export", "sync", "archive", "counts", "System"],
    type: "action",
    writer: { kind: "endpoint", method: "POST", path: "/sync/export" },
  },
  // ── Infrastructure (read-only env rows, collapsed) ─────────────────────────
  {
    id: "system.infra.bifrostUrl",
    category: "system",
    group: "infra",
    level: "advanced",
    label: "Bifrost URL",
    helpText: "Internal service mesh URL. Set BIFROST_URL in .env.",
    scopeOfEffect: { scope: "env", display: "Read-only here — set BIFROST_URL in .env and restart." },
    keywords: ["bifrost", "URL", "service", "mesh", "infra", "System"],
    type: "display",
    writer: { kind: "env", envVar: "BIFROST_URL" },
  },
  {
    id: "system.infra.chromaUrl",
    category: "system",
    group: "infra",
    level: "advanced",
    label: "ChromaDB URL",
    helpText: "Vector store endpoint. Set CHROMA_URL in .env.",
    scopeOfEffect: { scope: "env", display: "Read-only here — set CHROMA_URL in .env and restart." },
    keywords: ["chroma", "chromadb", "vector", "store", "URL", "System"],
    type: "display",
    writer: { kind: "env", envVar: "CHROMA_URL" },
  },
  {
    id: "system.infra.neo4jUri",
    category: "system",
    group: "infra",
    level: "advanced",
    label: "Neo4j URI",
    helpText: "Graph database URI. Set NEO4J_URI in .env.",
    scopeOfEffect: { scope: "env", display: "Read-only here — set NEO4J_URI in .env and restart." },
    keywords: ["neo4j", "graph", "URI", "database", "System"],
    type: "display",
    writer: { kind: "env", envVar: "NEO4J_URI" },
  },
  {
    id: "system.infra.archivePath",
    category: "system",
    group: "infra",
    level: "advanced",
    label: "Archive path",
    helpText: "Filesystem path where archived files are stored. Set ARCHIVE_PATH in .env.",
    scopeOfEffect: { scope: "env", display: "Read-only here — set ARCHIVE_PATH in .env and restart." },
    keywords: ["archive", "path", "storage", "files", "System"],
    type: "display",
    writer: { kind: "env", envVar: "ARCHIVE_PATH" },
  },
  {
    id: "system.infra.chunkingMode",
    category: "system",
    group: "infra",
    level: "advanced",
    label: "Chunking mode",
    helpText: "Text-splitting strategy used at ingest time. Set CHUNKING_MODE in .env.",
    scopeOfEffect: { scope: "env", display: "Read-only here — set CHUNKING_MODE in .env and restart." },
    keywords: ["chunking", "mode", "split", "ingest", "CHUNKING_MODE", "System"],
    type: "display",
    writer: { kind: "env", envVar: "CHUNKING_MODE" },
  },
  {
    id: "system.infra.syncBackend",
    category: "system",
    group: "infra",
    level: "advanced",
    label: "Sync backend",
    helpText: "Which backend stores the sync archive (local, S3, etc.). Set SYNC_BACKEND in .env.",
    scopeOfEffect: { scope: "env", display: "Read-only here — set SYNC_BACKEND in .env and restart." },
    keywords: ["sync", "backend", "storage", "SYNC_BACKEND", "System"],
    type: "display",
    writer: { kind: "env", envVar: "SYNC_BACKEND" },
  },
  // ── No-UI backend toggles (read-only, env-hint, searchable) ────────────────
  {
    id: "system.toggles.memoryRecall",
    category: "system",
    group: "toggles",
    level: "advanced",
    label: "Memory recall",
    helpText: "Enables episodic memory recall during conversation turns. Toggle enable_memory_recall in FEATURE_TOGGLES (env-only — no UI writer).",
    scopeOfEffect: { scope: "env", display: "Read-only here — set via server environment." },
    keywords: ["memory", "recall", "episodic", "enable_memory_recall", "Pipeline"],
    type: "display",
    writer: { kind: "env", envVar: "CERID_FEATURE_memory_recall" },
  },
  {
    id: "system.toggles.parentChildRetrieval",
    category: "system",
    group: "toggles",
    level: "advanced",
    label: "Parent–child retrieval",
    helpText: "Retrieves parent chunks when a child chunk scores high, giving more context. Toggle enable_parent_child_retrieval in FEATURE_TOGGLES (env-only).",
    scopeOfEffect: { scope: "env", display: "Read-only here — set via server environment." },
    keywords: ["parent", "child", "retrieval", "chunk", "context", "enable_parent_child_retrieval", "Pipeline"],
    type: "display",
    writer: { kind: "env", envVar: "CERID_FEATURE_parent_child_retrieval" },
  },
  {
    id: "system.toggles.contradictionLedger",
    category: "system",
    group: "toggles",
    level: "advanced",
    label: "Contradiction ledger",
    helpText: "Tracks claim contradictions across knowledge domains. Toggle enable_contradiction_ledger in FEATURE_TOGGLES (env-only).",
    scopeOfEffect: { scope: "env", display: "Read-only here — set via server environment." },
    keywords: ["contradiction", "ledger", "claims", "enable_contradiction_ledger", "Pipeline"],
    type: "display",
    writer: { kind: "env", envVar: "CERID_FEATURE_contradiction_ledger" },
  },
  // KB maintenance actions (rebuild / rescore / regenerate / clear-domain)
  // moved to the Knowledge category's `maintenance` group (ST12, 2026-06-22) —
  // they operate on the knowledge base, so they belong with it.
]
