// Copyright (c) 2026 Cerid AI. All rights reserved.
// SPDX-License-Identifier: FSL-1.1-ALv2

/**
 * TanStack Query hooks for the Briefs pane (Task 2.2).
 *
 * Briefs are generated by a daily/weekly cron job — a longer staleTime
 * than live-metrics surfaces is appropriate; no refetchInterval since new
 * briefs land at most a few times a day.
 */

import { useQuery, type QueryObserverResult } from "@tanstack/react-query"
import { fetchBriefs } from "@/lib/api/briefs"
import type { Brief, BriefKind } from "@/lib/types/brief"

// ---------------------------------------------------------------------------
// Brief list
// ---------------------------------------------------------------------------

export function useBriefs(kind: BriefKind): {
  data: Brief[] | undefined
  isLoading: boolean
  isError: boolean
  refetch: () => Promise<QueryObserverResult<Brief[], Error>>
} {
  const { data, isLoading, isError, refetch } = useQuery({
    queryKey: ["briefs", kind],
    queryFn: () => fetchBriefs(kind),
    staleTime: 5 * 60_000,
    retry: 1,
  })

  return { data, isLoading, isError, refetch }
}
