# Copyright (c) 2026 Cerid AI. All rights reserved.
# SPDX-License-Identifier: FSL-1.1-ALv2

"""Briefs read API (Task 2.1a).

Routes
------
GET  /briefs              List recent daily/weekly briefs, newest first.
GET  /briefs/{brief_id}   Fetch a single brief with hydrated claims.

Briefs are generated by the ``BriefGenerationJob`` / ``WeeklySynthesisJob``
processors (``app/processor/jobs/brief_generation.py`` /
``weekly_synthesis.py``) but had no read surface until this router. Claim
``band`` values are populated by a separate verification pass (not yet
shipped); a claim with no stored band renders as ``"unverified"`` here —
never fabricated as ``"verified"``.
"""
from __future__ import annotations

import logging
from datetime import timedelta
from typing import Literal

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

from core.utils.swallowed import log_swallowed_error

logger = logging.getLogger("ai-companion.briefs.api")

router = APIRouter(prefix="/briefs", tags=["briefs"])

__all__ = ["router"]

_Band = Literal["verified", "partial", "unverified"]


# ---------------------------------------------------------------------------
# Response models
# ---------------------------------------------------------------------------


class ClaimView(BaseModel):
    """A single claim cited by a brief."""

    text: str
    band: Literal["verified", "partial", "unverified"]
    source_ids: list[str]


class BriefSection(BaseModel):
    """One named section of brief markdown (e.g. ``CONNECTIONS``)."""

    title: str
    body: str


class BriefView(BaseModel):
    """A rendered brief: sections plus the claims it cites."""

    id: str
    kind: str
    generated_at: str
    sections: list[BriefSection]
    claims: list[ClaimView]
    # UX-18 — a brief generated before a large ingest must say so. Both
    # fields are computed at read time from artifacts ingested after
    # generation, inside the brief's own window (P1D daily / P7D weekly).
    stale: bool = False
    new_items_since_generation: int = 0


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _normalize_band(band: object, *, claim_id: object = None, brief_id: str | None = None) -> _Band:
    """Map a stored (possibly missing/garbage) band value to a safe Literal.

    Defaults to "unverified" — the safe default until the generation-time
    verification pass (sibling task 2.1b) populates real bands. Never
    fabricates "verified". A missing band (``None``) is expected until
    that pass ships and stays quiet; any *other* unrecognized value (e.g.
    a leaked ``"uncertain"``) is graph data-quality drift and is logged
    so it doesn't go unnoticed.
    """
    if band == "verified":
        return "verified"
    if band == "partial":
        return "partial"
    if band is not None and band != "unverified":
        logger.warning(
            "unexpected claim band value %r (claim_id=%s brief_id=%s); "
            "defaulting to 'unverified'",
            band, claim_id, brief_id,
        )
    return "unverified"


def _claim_view(raw: dict, *, brief_id: str) -> ClaimView:
    """Build a ClaimView from a hydrate_claims() row, defaulting missing fields.

    A missing text falls back to the claim_id (or empty string) so the
    API never crashes on partially-hydrated claim data.
    """
    text = raw.get("text") or raw.get("claim_id") or ""
    return ClaimView(
        text=text,
        band=_normalize_band(raw.get("band"), claim_id=raw.get("claim_id"), brief_id=brief_id),
        source_ids=list(raw.get("source_ids") or []),
    )


def _brief_view(record, claims: list[dict], *, new_items: int = 0) -> BriefView:
    return BriefView(
        id=record.brief_id,
        kind=record.kind,
        generated_at=record.generated_at.isoformat(),
        sections=[
            BriefSection(title=title, body=body)
            for title, body in record.sections.items()
        ],
        claims=[_claim_view(c, brief_id=record.brief_id) for c in claims],
        stale=new_items >= _STALE_MIN_NEW_ITEMS,
        new_items_since_generation=new_items,
    )


# UX-18 — "materially changed": below this many post-generation artifacts a
# brief is merely a little behind; at or above it, the brief is describing a
# different day than the one that happened (the motivating case was 443 mail
# messages landing after a 6am "empty inbox" brief).
_STALE_MIN_NEW_ITEMS = 5

# How long after generation new data still belongs to the brief's window.
_WINDOW_BY_KIND = {"daily": timedelta(days=1), "weekly": timedelta(days=7)}


def _new_item_counts(driver, records) -> dict[str, int]:
    """Post-generation artifact counts per brief, {} on any failure.

    Isolated so a staleness-count crash degrades to "not stale" instead of
    taking the whole brief list down with it.
    """
    from app.db.neo4j.briefs import count_artifacts_since_generation

    specs = []
    for record in records:
        window = _WINDOW_BY_KIND.get(record.kind, timedelta(days=1))
        specs.append(
            {
                "brief_id": record.brief_id,
                "generated_at": record.generated_at.isoformat(),
                "window_end": (record.generated_at + window).isoformat(),
            }
        )
    try:
        return count_artifacts_since_generation(driver, specs)
    except Exception as exc:  # noqa: BLE001
        log_swallowed_error("briefs.api.new_item_counts", exc)
        return {}


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.get("", response_model=list[BriefView], summary="List recent briefs")
async def list_briefs_endpoint(
    kind: Literal["daily", "weekly"] = Query(
        ..., description="Brief kind to list — 'daily' or 'weekly'.",
    ),
    limit: int = Query(default=20, ge=1, le=100),
) -> list[BriefView]:
    """Return recent briefs of the given kind, newest first, claims hydrated."""
    from app.db.neo4j.briefs import hydrate_claims_for_briefs, list_briefs
    from app.deps import get_neo4j

    try:
        driver = get_neo4j()
        records = list_briefs(driver, kind=kind, limit=limit)
        claims_by_brief_id = hydrate_claims_for_briefs(
            driver, [record.brief_id for record in records]
        )
        new_item_counts = _new_item_counts(driver, records)
        return [
            _brief_view(
                record,
                claims_by_brief_id.get(record.brief_id, []),
                new_items=new_item_counts.get(record.brief_id, 0),
            )
            for record in records
        ]
    except Exception as exc:  # noqa: BLE001
        log_swallowed_error("briefs.api.list", exc)
        return []


@router.get("/{brief_id}", response_model=BriefView, summary="Get a single brief")
async def get_brief_endpoint(brief_id: str) -> BriefView:
    """Fetch a single brief by id, 404 if unknown."""
    if brief_id == "settings":
        # Defensive: the static /briefs/settings route (app.routers.brief_settings)
        # is registered ahead of this dynamic route and should win, but a stray
        # brief literally named "settings" must never masquerade as that route.
        raise HTTPException(status_code=404, detail="Brief not found")

    from app.db.neo4j.briefs import get_brief, hydrate_claims
    from app.deps import get_neo4j

    try:
        driver = get_neo4j()
        record = get_brief(driver, brief_id)
    except Exception as exc:  # noqa: BLE001
        log_swallowed_error("briefs.api.get", exc)
        raise HTTPException(status_code=500, detail="Failed to fetch brief") from exc

    if record is None:
        raise HTTPException(status_code=404, detail="Brief not found")

    try:
        claims = hydrate_claims(driver, brief_id)
    except Exception as exc:  # noqa: BLE001
        log_swallowed_error("briefs.api.get_claims", exc)
        # A hydration failure must surface loudly (500), not as claims:[] —
        # that shape is reserved for a brief that genuinely cites nothing.
        raise HTTPException(status_code=500, detail="Failed to fetch brief") from exc

    new_item_counts = _new_item_counts(driver, [record])
    return _brief_view(
        record, claims, new_items=new_item_counts.get(record.brief_id, 0)
    )
