# Copyright (c) 2026 Cerid AI. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Contradiction ledger service (Phase W.4).

Provides the public surface for persisting and retrieving contradiction
findings detected by the NLI guard in
:mod:`core.agents.hallucination.verification`.

Layering
--------
* This module lives in ``app/services/`` — it may import from ``core.*``
  and from ``app.db.neo4j.contradictions``.
* It MUST NOT be imported by anything in ``core/`` (enforced by
  import-linter contract).
* The Neo4j driver is obtained lazily at call time via
  :func:`app.deps.get_neo4j` so the module is importable without a live
  database (unit tests mock the adapter instead).

Usage example (from the NLI guard, future Phase W.4 integration)::

    from app.services.contradiction_log import ContradictionFinding, log_contradiction

    finding = ContradictionFinding(
        finding_id=uuid4().hex,
        claim_a_id="claim-001",
        claim_b_id="claim-002",
        claim_a_text="The sky is blue.",
        claim_b_text="The sky is green.",
        severity="high",
        detected_at=utcnow_iso(),
    )
    await log_contradiction(finding)
"""
from __future__ import annotations

import logging
import uuid
from typing import Any, Literal

from pydantic import BaseModel

from app.db.neo4j import contradictions as _neo4j_adapter
from core.utils.swallowed import log_swallowed_error
from core.utils.time import utcnow_iso

logger = logging.getLogger("ai-companion.contradiction_log")

SeverityLiteral = Literal["low", "medium", "high"]


class ContradictionFinding(BaseModel):
    """Immutable record of a detected contradiction between two claims.

    Attributes
    ----------
    finding_id:
        Stable unique identifier (UUID hex or similar). Generated by the
        caller — the service layer does not auto-generate IDs so that the
        NLI guard can correlate the persisted finding with its in-process
        state without a round-trip.
    claim_a_id / claim_b_id:
        Stable identifiers for the two contradicting claims. Used to
        create or merge ``(:Claim)`` nodes in Neo4j.
    claim_a_text / claim_b_text:
        Human-readable text of each claim. Stored denormalized on the
        ContradictionFinding node for fast list rendering.
    entity_slug:
        Optional. Slug of the entity this contradiction is associated
        with (e.g. ``"elon-musk"``). Used to surface contradictions on
        entity wiki pages.
    severity:
        Coarse severity band. ``"high"`` means the two claims directly
        negate each other; ``"medium"`` means the claims are in tension
        with material overlap; ``"low"`` means a potential inconsistency
        that may reflect evolving context.
    detected_at:
        ISO-8601 timestamp when the contradiction was detected.
    query_ctx_id:
        Optional. Correlation ID of the query context that triggered
        detection — useful for linking back to the originating request.
    source_artifacts:
        List of artifact IDs (or other provenance identifiers) whose
        content surfaced the contradicting claims.
    """

    finding_id: str
    claim_a_id: str
    claim_b_id: str
    claim_a_text: str
    claim_b_text: str
    entity_slug: str | None = None
    severity: SeverityLiteral = "medium"
    detected_at: str = ""
    query_ctx_id: str | None = None
    source_artifacts: list[str] = []

    def model_post_init(self, __context: Any) -> None:
        """Back-fill detected_at to now if not provided by the caller."""
        if not self.detected_at:
            object.__setattr__(self, "detected_at", utcnow_iso())


def _build_finding_from_row(row: dict[str, Any]) -> ContradictionFinding:
    """Convert a raw Neo4j property dict back to a :class:`ContradictionFinding`."""
    source_artifacts_raw = row.get("source_artifacts", "")
    source_artifacts: list[str] = (
        [s for s in source_artifacts_raw.split(",") if s]
        if isinstance(source_artifacts_raw, str)
        else list(source_artifacts_raw)
    )
    return ContradictionFinding(
        finding_id=row["finding_id"],
        claim_a_id=row.get("claim_a_id", ""),
        claim_b_id=row.get("claim_b_id", ""),
        claim_a_text=row.get("claim_a_text", ""),
        claim_b_text=row.get("claim_b_text", ""),
        entity_slug=row.get("entity_slug") or None,
        severity=row.get("severity", "medium"),
        detected_at=row.get("detected_at", ""),
        query_ctx_id=row.get("query_ctx_id") or None,
        source_artifacts=source_artifacts,
    )


async def log_contradiction(finding: ContradictionFinding) -> str:
    """Persist a contradiction finding to the Neo4j graph.

    Parameters
    ----------
    finding:
        Fully-populated :class:`ContradictionFinding`. The caller is
        responsible for generating a stable ``finding_id`` (e.g.
        ``uuid.uuid4().hex``).

    Returns
    -------
    str
        The ``finding_id`` that was persisted. Equal to
        ``finding.finding_id`` on success.

    Raises
    ------
    Exception
        Propagates Neo4j driver errors after logging them via
        :func:`core.utils.swallowed.log_swallowed_error`.
    """
    from app.deps import get_neo4j

    driver = get_neo4j()
    try:
        result = _neo4j_adapter.record_contradiction(driver, finding)
    except Exception as exc:
        log_swallowed_error("contradiction_log", exc, context={"finding_id": finding.finding_id})
        raise

    # Phase K2.3 — emit contradiction_detected event so the wiki refresh
    # subscriber can fire immediately (force=True bypasses debounce —
    # when the corpus disagrees with itself, the user deserves a fresh
    # summary now). No-op when no entity slug is attached.
    if finding.entity_slug:
        try:
            from app.processor.event_hooks import emit  # noqa: PLC0415

            emit("contradiction_detected", {
                "finding_id": finding.finding_id,
                "entity_slug": finding.entity_slug,
                "severity": finding.severity,
            })
        except Exception as exc:  # noqa: BLE001 — observability boundary
            log_swallowed_error(
                "contradiction_log.emit_event",
                exc,
                context={"finding_id": finding.finding_id},
            )

    return result


async def list_recent(
    *,
    entity_slug: str | None = None,
    since: str | None = None,
    limit: int = 100,
) -> list[ContradictionFinding]:
    """Return a paginated list of contradiction findings.

    Parameters
    ----------
    entity_slug:
        Optional filter by associated entity slug.
    since:
        Optional ISO-8601 lower bound on ``detected_at``.
    limit:
        Maximum number of results (server-side cap: 1000).

    Returns
    -------
    list[ContradictionFinding]
        Findings ordered by ``detected_at`` descending (newest first).
    """
    from app.deps import get_neo4j

    driver = get_neo4j()
    try:
        rows = _neo4j_adapter.list_contradictions(
            driver,
            entity_slug=entity_slug,
            since=since,
            limit=limit,
        )
        return [_build_finding_from_row(r) for r in rows]
    except Exception as exc:
        log_swallowed_error("contradiction_log", exc, context={"entity_slug": entity_slug})
        raise


async def get_by_id(finding_id: str) -> ContradictionFinding | None:
    """Fetch a single finding by its stable identifier.

    Returns ``None`` if not found; propagates driver errors after logging.
    """
    from app.deps import get_neo4j

    driver = get_neo4j()
    try:
        row = _neo4j_adapter.get_contradiction(driver, finding_id)
        if row is None:
            return None
        return _build_finding_from_row(row)
    except Exception as exc:
        log_swallowed_error("contradiction_log", exc, context={"finding_id": finding_id})
        raise


async def get_by_entity(
    entity_slug: str,
    *,
    limit: int = 100,
) -> list[ContradictionFinding]:
    """Convenience wrapper: all findings for a given entity slug.

    Thin alias over :func:`list_recent` with entity_slug required.
    """
    return await list_recent(entity_slug=entity_slug, limit=limit)


def make_finding_id() -> str:
    """Generate a new stable finding ID suitable for use with log_contradiction."""
    return uuid.uuid4().hex
