#!/usr/bin/env python3
# Copyright (c) 2026 Cerid AI. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate .env.example from src/mcp/config/settings.py os.getenv calls.

Walks the AST of settings.py and emits a sorted .env.example file with
each discovered env var and its default value (if a simple string literal).

Usage:
    python scripts/gen_env_example.py                 # regenerate, write to .env.example
    python scripts/gen_env_example.py --check         # exit 1 if the file is out of sync (CI mode)
"""
from __future__ import annotations

import argparse
import ast
import difflib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SETTINGS_FILE = REPO_ROOT / "src" / "mcp" / "config" / "settings.py"
ENV_EXAMPLE_FILE = REPO_ROOT / ".env.example"


class GetenvVisitor(ast.NodeVisitor):
    """Collect (name, default) pairs from os.getenv(...) calls."""

    def __init__(self) -> None:
        self.entries: list[tuple[str, str | None]] = []

    def visit_Call(self, node: ast.Call) -> None:  # noqa: N802
        # Match os.getenv("NAME", [default]) or os.environ.get("NAME", [default])
        if self._is_getenv_call(node) and node.args:
            name_node = node.args[0]
            if isinstance(name_node, ast.Constant) and isinstance(name_node.value, str):
                default = self._extract_default(node.args[1]) if len(node.args) > 1 else None
                self.entries.append((name_node.value, default))
        self.generic_visit(node)

    @staticmethod
    def _is_getenv_call(node: ast.Call) -> bool:
        func = node.func
        if isinstance(func, ast.Attribute):
            if func.attr == "getenv" and isinstance(func.value, ast.Name) and func.value.id == "os":
                return True
            # os.environ.get(...)
            if (
                func.attr == "get"
                and isinstance(func.value, ast.Attribute)
                and func.value.attr == "environ"
                and isinstance(func.value.value, ast.Name)
                and func.value.value.id == "os"
            ):
                return True
        return False

    @staticmethod
    def _extract_default(node: ast.expr) -> str | None:
        if isinstance(node, ast.Constant):
            return str(node.value) if node.value is not None else None
        return None  # complex defaults (f-strings, variables) not rendered


def extract_env_vars(source: str) -> list[tuple[str, str | None]]:
    tree = ast.parse(source)
    visitor = GetenvVisitor()
    visitor.visit(tree)
    # Dedup; keep first seen occurrence
    seen: dict[str, str | None] = {}
    for name, default in visitor.entries:
        if name not in seen:
            seen[name] = default
    return sorted(seen.items())


def render_env_example(entries: list[tuple[str, str | None]]) -> str:
    lines = [
        "# .env.example — auto-generated from src/mcp/config/settings.py",
        "# Generated by scripts/gen_env_example.py — do not edit by hand.",
        "# Regenerate with: python scripts/gen_env_example.py",
        "",
    ]
    for name, default in entries:
        if default is not None:
            lines.append(f"{name}={default}")
        else:
            lines.append(f"{name}=")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the tracked .env.example is out of sync with settings.py (CI mode)",
    )
    args = parser.parse_args(argv)

    source = SETTINGS_FILE.read_text(encoding="utf-8")
    entries = extract_env_vars(source)
    expected = render_env_example(entries)

    if args.check:
        if not ENV_EXAMPLE_FILE.exists():
            print(".env.example missing — run: python scripts/gen_env_example.py", file=sys.stderr)
            return 1
        actual = ENV_EXAMPLE_FILE.read_text(encoding="utf-8")
        if actual != expected:
            print(
                ".env.example is out of sync with settings.py. "
                "Regenerate with: python scripts/gen_env_example.py",
                file=sys.stderr,
            )
            diff = list(
                difflib.unified_diff(
                    actual.splitlines(),
                    expected.splitlines(),
                    fromfile=".env.example (tracked)",
                    tofile=".env.example (generated)",
                    lineterm="",
                )
            )
            for line in diff[:40]:
                print(line, file=sys.stderr)
            return 1
        print(f".env.example is in sync ({len(entries)} env vars).")
        return 0

    ENV_EXAMPLE_FILE.write_text(expected)
    print(f"Wrote {len(entries)} env vars to {ENV_EXAMPLE_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
