#!/usr/bin/env python3
# Copyright (c) 2026 Justin Michaels. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Forbid `.d.ts` files sharing a basename with sibling `.ts` files.

Graduates lesson ``tasks/lessons.md::"`.d.ts` files with same basename
as `.ts` files conflict"``. When `syntax-highlighter.d.ts` lives next
to `syntax-highlighter.ts`, TypeScript treats the `.d.ts` as the type
declaration for that specific module rather than as ambient `declare
module` declarations. Any `declare module` statements inside are
silently ignored — the cause of the original 1.6 MB bundle-size
regression.

Rule: `.d.ts` ambient declaration files must have a basename distinct
from every `.ts` / `.tsx` file in the same directory. (Co-located
`.d.ts` files generated by the build for matching `.ts` are different
— those aren't checked in.)

Scans `src/web/src/` only (no equivalent issue in the Python layer).

Usage::

    python3 scripts/lint-dts-basename-collision.py
    python3 scripts/lint-dts-basename-collision.py --warn-only
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
WEB_ROOT = REPO_ROOT / "src" / "web" / "src"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--warn-only", action="store_true")
    args = ap.parse_args()

    if not WEB_ROOT.exists():
        print(f"web root {WEB_ROOT} missing — skipping")
        return 0

    findings: list[str] = []
    for dts in WEB_ROOT.rglob("*.d.ts"):
        if "node_modules" in dts.parts:
            continue
        # The .d.ts basename without the .d.ts suffix.
        stem = dts.name[: -len(".d.ts")]
        sibling_ts = dts.parent / f"{stem}.ts"
        sibling_tsx = dts.parent / f"{stem}.tsx"
        if sibling_ts.exists() or sibling_tsx.exists():
            collide = sibling_ts if sibling_ts.exists() else sibling_tsx
            findings.append(
                f"{dts.relative_to(REPO_ROOT)}: basename collides with "
                f"{collide.relative_to(REPO_ROOT)} — ambient `declare module` "
                "statements will be silently ignored. Rename the .d.ts to "
                f"e.g. `{stem}-types.d.ts`."
            )

    if findings:
        print(
            "Ambient .d.ts shares basename with sibling .ts — graduates lessons.md L5:\n"
            "(TS treats it as the type decl for that module instead of ambient)\n"
        )
        for f in findings:
            print(f"  {f}")
        return 0 if args.warn_only else 1

    print("dts-basename-collision: web tree compliant.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
