// Copyright (c) 2026 Cerid AI. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Runtime config precedence (highest first):
//   1. window.cerid.env  — injected by the Electron desktop preload. Lets the
//      desktop "remote server" mode point the bundled UI at a LAN backend (and
//      pass its API key) without a rebuild, since the file:// bundle has no
//      docker-entrypoint to generate env-config.js.
//   2. window.__ENV__    — generated by docker-entrypoint.sh at container boot.
//   3. import.meta.env   — build-time Vite vars.
// A relative "/api/mcp" (nginx proxy) is the final fallback for the web build.
const _ceridEnv = ((globalThis as Record<string, unknown>).cerid as { env?: Record<string, string> } | undefined)?.env
const _winEnv = (globalThis as Record<string, unknown>).__ENV__ as Record<string, string> | undefined
const _env: Record<string, string> = { ..._winEnv, ..._ceridEnv }
const _rawMcpUrl = _env.VITE_MCP_URL || import.meta.env.VITE_MCP_URL || "/api/mcp"

// Self-healing: if the configured MCP URL points to a non-localhost host:port
// and we're served from localhost (Docker nginx proxy), prefer /api/mcp.
// This handles stale env-config.js cached by the browser.
function _resolveBaseUrl(raw: string): string {
  if (typeof window === "undefined") return raw
  // If we're on localhost but MCP URL points elsewhere, use the nginx proxy
  const isLocalOrigin = window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1"
  const isDirectPort = /^https?:\/\/[\d.]+:\d+/.test(raw) && !raw.includes("localhost") && !raw.includes("127.0.0.1")
  if (isLocalOrigin && isDirectPort) {
    return "/api/mcp"
  }
  return raw
}

export const MCP_BASE = _resolveBaseUrl(_rawMcpUrl)
// API key read from runtime injection ONLY — never from build-time env (would be baked into bundle)
const API_KEY = _env.VITE_CERID_API_KEY || ""

import { uuid } from "@/lib/utils"
import { logSwallowedError } from "@/lib/log-swallowed"

export function mcpHeaders(extra: Record<string, string> = {}): Record<string, string> {
  const headers: Record<string, string> = { ...extra }
  headers["X-Client-ID"] = "gui"
  if (API_KEY) headers["X-API-Key"] = API_KEY
  headers["X-Request-ID"] = uuid()
  // Add JWT Bearer token if authenticated (multi-user mode)
  try {
    const token = localStorage.getItem("cerid-access-token")
    if (token) headers["Authorization"] = `Bearer ${token}`
  } catch (err) { logSwallowedError(err, "localStorage.getItem", { key: "cerid-access-token" }) }
  return headers
}

/**
 * Build an absolute URL for an MCP API path. `MCP_BASE` may be a relative
 * prefix ("/api/mcp"), so `new URL(relativePath)` throws "Invalid URL"; and a
 * fetch that forgets the prefix silently falls through nginx to the SPA shell
 * (HTTP 200 text/html, which then explodes on `.json()`). Routing every MCP
 * request through this helper prevents both error classes: always prefix
 * MCP_BASE, always anchor to the current origin.
 */
export function mcpUrl(
  path: string,
  params?: Record<string, string | number | null | undefined>,
): URL {
  const origin = typeof window !== "undefined" ? window.location.origin : "http://localhost"
  const url = new URL(`${MCP_BASE}${path}`, origin)
  if (params) {
    for (const [key, value] of Object.entries(params)) {
      if (value !== null && value !== undefined) url.searchParams.set(key, String(value))
    }
  }
  return url
}

export async function extractError(res: Response, fallback: string): Promise<string> {
  try {
    const body = await res.json()
    // CeridError format: { error_code, message, details }
    if (body.error_code && body.message) {
      return `[${body.error_code}] ${body.message}`
    }
    // FastAPI 422: detail is an array of { loc, msg, type } records.
    if (Array.isArray(body.detail)) {
      return body.detail
        .map((d: { loc?: unknown[]; msg?: string }) => {
          const field = Array.isArray(d.loc) ? d.loc.slice(1).join(".") : ""
          return field ? `${field}: ${d.msg ?? ""}` : (d.msg ?? "")
        })
        .filter(Boolean)
        .join("; ") || fallback
    }
    // Legacy format: { detail: "..." }
    return typeof body.detail === "string" ? body.detail : fallback
  } catch {
    return fallback
  }
}

/** Parsed structured error with typed discriminators. */
export interface ParsedError {
  message: string
  error_code?: string
  details?: Record<string, unknown>
  isFeatureGate: boolean
  isCreditExhausted: boolean
  isRateLimit: boolean
}

/** Parse CeridError structured response — handles both new and legacy error formats. */
export async function parseStructuredError(res: Response, fallback: string): Promise<ParsedError> {
  try {
    const body = await res.json()
    const code: string = body.error_code ?? ""
    return {
      message: body.message ?? body.detail ?? fallback,
      error_code: code || undefined,
      details: body.details ?? undefined,
      isFeatureGate: code.startsWith("FEATURE_GATE_"),
      isCreditExhausted: code.startsWith("PROVIDER_CREDIT_"),
      isRateLimit: code.startsWith("PROVIDER_RATE_"),
    }
  } catch {
    return { message: fallback, isFeatureGate: false, isCreditExhausted: false, isRateLimit: false }
  }
}
