#!/bin/bash
# Beta test markdown report generator
# Source this file in the orchestrator: source "$(dirname "$0")/lib/report.sh"

REPORT_FILE=""
REPORT_DIR=""
_ISSUE_COUNT=0

report_init() {
  REPORT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/reports"
  mkdir -p "$REPORT_DIR"
  local ts
  ts=$(date '+%Y-%m-%d-%H%M%S')
  REPORT_FILE="${REPORT_DIR}/beta-report-${ts}.md"

  local git_rev os_ver docker_ver
  git_rev=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
  os_ver=$(sw_vers -productVersion 2>/dev/null || uname -r)
  docker_ver=$(docker --version 2>/dev/null | head -1 || echo "unknown")

  cat > "$REPORT_FILE" <<HEADER
# Cerid AI — Beta Test Report

**Date:** $(date '+%Y-%m-%d %H:%M:%S %Z')
**Git revision:** ${git_rev}
**Environment:** macOS ${os_ver}, ${docker_ver}
**Harness version:** 1.0.0

---
HEADER
  echo "$REPORT_FILE"
}

report_section() {
  local title="$1"
  [[ -z "$REPORT_FILE" ]] && return
  {
    echo ""
    echo "## ${title}"
    echo ""
    echo "| ID | Test | Result | Duration | Notes |"
    echo "|----|------|--------|----------|-------|"
  } >> "$REPORT_FILE"
}

# Append results from a RESULTS_FILE into the current section
report_append_results() {
  local results_file="$1"
  [[ -z "$REPORT_FILE" || ! -f "$results_file" ]] && return
  while IFS='|' read -r status id name duration notes; do
    local icon
    case "$status" in
      PASS) icon="✅" ;;
      FAIL) icon="❌" ;;
      SKIP) icon="⊘" ;;
      *) icon="?" ;;
    esac
    echo "| ${id} | ${name} | ${icon} ${status} | ${duration} | ${notes} |" >> "$REPORT_FILE"
  done < "$results_file"
}

report_issue() {
  local severity="$1" title="$2" category="$3" test_id="$4" component="$5"
  local steps="$6" expected="$7" actual="$8" evidence="${9:-}" fix="${10:-}"
  [[ -z "$REPORT_FILE" ]] && return
  _ISSUE_COUNT=$((_ISSUE_COUNT + 1))
  local num
  num=$(printf "%03d" $_ISSUE_COUNT)

  # Add issues section header on first issue
  if [[ $_ISSUE_COUNT -eq 1 ]]; then
    {
      echo ""
      echo "---"
      echo ""
      echo "## Issues Found"
      echo ""
    } >> "$REPORT_FILE"
  fi

  {
    local sev_upper
    sev_upper=$(echo "$severity" | tr '[:lower:]' '[:upper:]')
    echo "### ISSUE-${num}: [${sev_upper}] ${title}"
    echo "- **Category:** ${category}"
    echo "- **Severity:** ${severity}"
    echo "- **Test ID:** ${test_id}"
    echo "- **Component:** ${component}"
    echo "- **Reproducible:** always"
    echo ""
    echo "**Steps to reproduce:**"
    echo "${steps}"
    echo ""
    echo "**Expected behavior:**"
    echo "${expected}"
    echo ""
    echo "**Actual behavior:**"
    echo "${actual}"
    echo ""
  } >> "$REPORT_FILE"
  [[ -n "$evidence" ]] && printf '**Evidence:**\n```\n%s\n```\n\n' "$evidence" >> "$REPORT_FILE"
  [[ -n "$fix" ]] && printf '**Suggested fix:**\n%s\n\n' "$fix" >> "$REPORT_FILE"
}

report_text() {
  [[ -z "$REPORT_FILE" ]] && return
  echo -e "$1" >> "$REPORT_FILE"
}

report_summary() {
  [[ -z "$REPORT_FILE" ]] && return
  local total_pass=0 total_fail=0 total_skip=0
  # Aggregate from all results files in reports/
  shopt -s nullglob
  local results_files=("${REPORT_DIR}"/*.results)
  shopt -u nullglob
  for rf in ${results_files[@]+"${results_files[@]}"}; do
    [[ -f "$rf" ]] || continue
    local c
    c=$(grep -c "^PASS|" "$rf" 2>/dev/null) || c=0; total_pass=$((total_pass + c))
    c=$(grep -c "^FAIL|" "$rf" 2>/dev/null) || c=0; total_fail=$((total_fail + c))
    c=$(grep -c "^SKIP|" "$rf" 2>/dev/null) || c=0; total_skip=$((total_skip + c))
  done
  local total=$((total_pass + total_fail + total_skip))

  local verdict="PASS"
  [[ $total_fail -gt 0 ]] && verdict="FAIL"

  local verdict_text
  if [[ "$verdict" == "PASS" ]]; then
    verdict_text="All tests passed. Beta is **GO**."
  elif [[ $_ISSUE_COUNT -le 3 ]]; then
    verdict_text="Issues found but within tolerance. Beta is **GO with caveats**."
  else
    verdict_text="Multiple failures detected. Beta is **NO-GO** pending fixes."
  fi

  # Insert summary at top of report (after header)
  local tmp
  tmp=$(mktemp)
  head -8 "$REPORT_FILE" > "$tmp"
  {
    echo ""
    echo "## Summary"
    echo ""
    echo "| Metric | Count |"
    echo "|--------|-------|"
    echo "| Total tests | ${total} |"
    echo "| Passed | ${total_pass} |"
    echo "| Failed | ${total_fail} |"
    echo "| Skipped | ${total_skip} |"
    echo "| Issues found | ${_ISSUE_COUNT} |"
    echo ""
    echo "**Overall verdict:** ${verdict}"
    echo ""
    echo "${verdict_text}"
    echo ""
  } >> "$tmp"
  tail -n +9 "$REPORT_FILE" >> "$tmp"
  mv "$tmp" "$REPORT_FILE"
}

report_finalize() {
  [[ -z "$REPORT_FILE" ]] && return
  report_summary
  {
    echo ""
    echo "---"
    echo ""
    echo "*Generated by Cerid AI Beta Test Harness v1.0.0*"
  } >> "$REPORT_FILE"
  echo ""
  echo "═══════════════════════════════════════════════"
  echo "  Report saved to: ${REPORT_FILE}"
  echo "═══════════════════════════════════════════════"
}
